name: Lint PR Titles
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install
        run: yarn install
      - name: Lint Pr titles
        uses: ./.github/actions/pr-linting
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          pr-title: ${{ github.event.pull_request.title }}